name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Prepare Gradle
        run: |
          chmod +x gradlew
          mkdir -p out

      - name: Build JRE
        run: |
          ./gradlew jre_lwjgl3glfw:build --no-daemon

      - name: Build APK
        run: |
          ./gradlew ZalithLauncher:assembleDebug -Darch=all --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ZalithLauncher-APK
          path: ZalithLauncher/build/outputs/apk/debug/*.apk
